version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 80:80
    container_name: frontend
    networks:
      - frontend
    depends_on:
      - backend

 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: always
    ports:
      - 5000:5000
    container_name: backend
    networks:
      - backend
      - frontend 
    volumes:
      - db:/data/db
    depends_on:
      - mongodb
 
  mongodb:
    image: mongo:5.0.2
    restart: always
    ports:
      - 27017:27017
    container_name: mongo-db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=ExpenseTracker01
    networks:
      - backend
    volumes:
      - db:/data/db

networks:
  backend:
  frontend:

volumes:
  db:
    name: mongo-db-data
    driver: local

