version: "3.9"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    container_name: frontend
    networks:
      - frontend
    depends_on:
      - backend

 
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3080:3080
    container_name: backend
    networks:
      - backend
      - frontend 
    volumes:
      - db:/data/db
    depends_on:
      - mongodb
 
  mongodb:
    image: mongo:5.0.2
    restart: unless-stopped
    ports:
      - 27017:27017
    container_name: mongo-db
    env_file: ./backend/.env.production
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD
    networks:
      - backend
    volumes:
      - db:/data/db

networks:
  backend:
  frontend:

volumes:
  db:
